session_name: openbroadcast_ch
start_directory: ./
windows:

- window_name: obp
  layout: tiled
  shell_command_before:
    - 'source ~/srv/openbroadcast.ch3/bin/activate'
  panes:
    - shell_command:
        - cd website
        - ./manage.py runserver 0.0.0.0:8081
    - shell_command:
        - cd website
        - celery -A project worker --beat -c 1 -l DEBUG
    - shell_command:
        - cd services/pushy
        - node pushy.js
    - npm run watch
