session_name: openbroadcast_ch
start_directory: ./
windows:

- window_name: obp
  layout: tiled
  shell_command_before:
    - 'source ~/srv/openbroadcast.ch/bin/activate'
    - 'export DJANGO_SETTINGS_MODULE=app.settings.local_development'
  panes:
    - shell_command:
        - ./manage.py runserver 0.0.0.0:8081
    - shell_command:
        - celery -A app worker --beat -c 1 -l INFO
    - npm run watch
    - ls
