version: '3'
services:
  redis:
    image: redis
  web:
    image: ch-openbroadcast:latest
    #command: daphne --port 8000 --bind 0.0.0.0 app.asgi:application
    environment:
      - DJANGO_MANAGE_MIGRATE=off
      - DJANGO_MANAGE_COLLECTSTATIC=off
      - DATABASE_URL=postgres://ohrstrom@docker.for.mac.localhost:5432/ch_openbroadcast_local
      - REDIS_URL=redis://redis:6379
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=app.settings.default
    depends_on:
      - redis
    ports:
      - 8090:8000
    links:
      - redis
  worker:
    image: ch-openbroadcast:latest
    command: celery -A app worker --beat -c 1 -l INFO
    environment:
      - DJANGO_MANAGE_MIGRATE=off
      - DJANGO_MANAGE_COLLECTSTATIC=off
      - DATABASE_URL=postgres://ohrstrom@docker.for.mac.localhost:5432/ch_openbroadcast_local
      - REDIS_URL=redis://redis:6379
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=app.settings.default
    depends_on:
      - redis
    links:
      - redis

volumes:
  pg_data_ch_openbroadcast:
