version: '3'
services:
  db:
    image: postgres:alpine
    volumes:
      - 'pg_data_ch_openbroadcast:/var/lib/postgresql/data/'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis

  app:
    image: ch-openbroadcast:latest
    #build: .
    #volumes:
    #    - ./app/:/app/app
    #command: /app/manage.py runserver 0.0.0.0:8000
    #command: daphne --port 8000 --bind 0.0.0.0 app.asgi:application
    environment:
      - DJANGO_MANAGE_MIGRATE=off
      - DJANGO_MANAGE_COLLECTSTATIC=off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=app.settings.default
    depends_on:
      - db
      - redis
    ports:
      - 8090:8000
    links:
      - db
      - redis

volumes:
  pg_data_ch_openbroadcast:
