# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-27 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0002_auto_20150721_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='options',
        ),
    ]
