# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-27 15:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onair', '0003_auto_20180827_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleditem',
            name='emission_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleditem',
            name='item_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
