# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-23 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentproxy', '0004_cachedmedia_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='CachedEvent',
        ),
    ]
