# Generated by Django 2.2.7 on 2019-12-04 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("heartbeat", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="session_key",
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="beat",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beat",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
