# Generated by Django 2.2.7 on 2019-12-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("heartbeat", "0002_auto_20191204_1543")]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        )
    ]
