# Generated by Django 2.2.7 on 2019-12-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("heartbeat", "0003_beat_ip")]

    operations = [
        migrations.AlterField(
            model_name="beat",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        )
    ]
