# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-27 15:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onair', '0002_auto_20160229_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleditem',
            name='emission_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='scheduleditem',
            name='item_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
