# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-06 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0015_auto_20160421_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('video_url', models.URLField(max_length=512)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Optional title to display')),
                ('theme', models.CharField(choices=[(b'light', 'light'), (b'dark', 'dark')], default=b'light', max_length=20, verbose_name='theme')),
                ('color', models.CharField(choices=[(b'white', 'white'), (b'red', 'red')], default=b'white', max_length=20, verbose_name='color')),
                ('ratio', models.FloatField(choices=[(1.33, b'3/4 (default)'), (1.78, b'16/9 (widescreen)'), (1.6, b'16/10 (widescreen)'), (1.4, b'14/10 (extra widescreen)')], default=1.78, verbose_name='ratio')),
            ],
            options={
                'db_table': 'cmsplugin_youtube',
                'verbose_name': 'YouTube',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
