# Generated by Django 2.2.7 on 2019-12-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnonymousVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("value", models.SmallIntegerField(blank=True, null=True)),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=64, null=True),
                ),
                ("obj_ct", models.CharField(db_index=True, max_length=64, null=True)),
                ("obj_uuid", models.CharField(db_index=True, max_length=36, null=True)),
            ],
            options={
                "verbose_name": "Anonymous Vote",
                "verbose_name_plural": "Anonymous Votes",
                "unique_together": {("session_key", "obj_ct", "obj_uuid")},
            },
        )
    ]
