# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-15 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StreamEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="request method",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="status code",
                    ),
                ),
                ("status", models.PositiveIntegerField(blank=True, null=True)),
                ("bytes_sent", models.PositiveIntegerField(blank=True, null=True)),
                ("referer", models.CharField(blank=True, max_length=500, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "seconds_connected",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("time_start", models.DateTimeField(blank=True, null=True)),
                ("time_end", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Stream Event",
                "verbose_name_plural": "Stream Event",
                "ordering": ("-created",),
            },
        )
    ]
